name: Robot Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Instalar Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg curl unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar ChromeDriver compatível
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f1)
          echo "Versão detectada do Chrome: $CHROME_VERSION"
          DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_${MAJOR_VERSION}")
          echo "Baixando ChromeDriver versão: $DRIVER_VERSION"
          wget -O /tmp/chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/${DRIVER_VERSION}/linux64/chromedriver-linux64.zip"
          unzip /tmp/chromedriver.zip -d /tmp/
          sudo mv /tmp/chromedriver-linux64/chromedriver /usr/local/bin/
          sudo ch
