name: Robot Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install selenium

      - name: Rodar testes Robot
        run: robot --outputdir results tests/

      - name: Guardar relatórios
        uses: actions/upload-artifact@v3
        with:
          name: relatorios-robot
          path: results/
